package com.urosjarc.slotraffic.domain

import kotlinx.serialization.Serializable

@Serializable
data class RestAreaProps(
    val EntityId: String,
    val Name: String,
    val Description: String?,
    val LocationDescription: String?,
    val GroupName: String,
    val Image: String?,
    val WorkingHours: String,
    val Odsek: String,
    val Stacionaza: Float,
    val X: Float,
    val Y: Float,
    val ParkingSpaces: Int?,
    val TruckParkingSpaces: Int?,
    val NameEN: String,
    val DescriptionEN: String?,
    val LocationDescriptionEN: String?,
    val GroupNameEN: String?,
    val WorkingHoursEN: String?,
    val HasParkirisce: Boolean,
    val HasBencinskiServis: Boolean,
    val HasAvtoplin: Boolean,
    val HasTrgovina: Boolean,
    val HasBar: Boolean,
    val HasRestavracija: Boolean,
    val HasStranisce: Boolean,
    val HasTelefon: Boolean,
    val HasOskrbaAvtodomov: Boolean,
    val HasOtroskaIgrala: Boolean,
    val HasProstorZaPocitek: Boolean,
    val HasRekreativnePovrsine: Boolean,
    val HasBankomat: Boolean,
    val HasTus: Boolean,
    val HasWiFi: Boolean,
    val OperatorName: String,
    val OperatorPhone: String,
    val OperatorEmail: String,
    val InterUrbanParkingSiteLocation: String,
    val AlertCLCD: Int,
    val AlertCOffset: Float,
    val AlertCDirection: String,
    val OznakaCeste: String,
    val OznakaCesteEn: String,
    val RoadDestination: String,
    val RoadDestinationEn: String,
    val ParkingSecurity: String,
    val RefrigeratedTruckParkingSpaces: String?,
    val IsActive: Boolean,
)
